/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EmployeeDisplayAddressText: typeof import('./components/employee/DisplayAddressText.vue')['default']
    EmployeeForm: typeof import('./components/employee/Form.vue')['default']
    EmployeeTable: typeof import('./components/employee/Table.vue')['default']
    EmployeeTableItem: typeof import('./components/employee/TableItem.vue')['default']
    EmployeeTableItemActions: typeof import('./components/employee/TableItemActions.vue')['default']
    EmployeeWidget: typeof import('./components/employee/Widget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
